name: Repositorio Reaproveitavel
on: 
    push:
      branches: ["main"]
    workflow_dispatch:

jobs: 
    CI:
        runs-on: ubuntu-latest
        steps:
            - name: Build da Imagem Docker
              run: echo "Imagem Docker construída com sucesso!"
    CD:
      needs: [CI]
      uses: casoftsolutions/repo-deploy/.github/workflows/main.yml@main
      with:
        ambiente: Meu teste #  esse valor sera usado no arquivo cd.yaml
        versao: 520
      secrets: inherit 

